theme: jekyll-theme-cayman
title: Colors Blend
description: Blending two Hex Colors has never been so simple!
license:
  name: MIT
  url: https://github.com/BenSouchet/colors-blend/blob/main/LICENSE
maintainers:
  - name: Ben Souchet
    url: https://github.com/BenSouchet
